# Generated by Django 4.2.3 on 2023-07-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactinfomodel_rename_bannermodel_homebannermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfomodel',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='phone'),
        ),
    ]
