# Generated by Django 4.2.3 on 2023-07-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactinfomodel_address_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfomodel',
            options={'verbose_name': 'contact info', 'verbose_name_plural': 'contact info'},
        ),
        migrations.RemoveField(
            model_name='contactinfomodel',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='contactinfomodel',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='contactinfomodel',
            name='sub_title_ru',
        ),
        migrations.RemoveField(
            model_name='contactinfomodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contactinfomodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='contactinfomodel',
            name='title_ru',
        ),
    ]
