# Generated by Django 4.2.3 on 2023-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_contactinfomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfomodel',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='phone'),
        ),
    ]
