# Generated by Django 4.2.3 on 2023-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_reservationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(max_length=100, verbose_name='discount_title')),
                ('sub_title', models.CharField(max_length=100, verbose_name='sub_title')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'reservation info',
                'verbose_name_plural': 'reservation info',
            },
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
