# Generated by Django 4.2.3 on 2023-08-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_reservationmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='name_ru',
        ),
    ]
