# Generated by Django 4.2.3 on 2023-07-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pretestimonialmodel',
            options={'verbose_name': 'pre testimonial', 'verbose_name_plural': 'pre testimonials'},
        ),
        migrations.AddField(
            model_name='aboutimagemodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutimagemodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='left_description_en',
            field=models.TextField(null=True, verbose_name='left_description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='left_description_ru',
            field=models.TextField(null=True, verbose_name='left_description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='left_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='left_title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='left_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='left_title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='right_description_en',
            field=models.TextField(null=True, verbose_name='right_description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='right_description_ru',
            field=models.TextField(null=True, verbose_name='right_description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='right_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='right_title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='right_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='right_title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='sub_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='sub_title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='sub_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='sub_title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='left_description'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='left_description'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='profession_en',
            field=models.CharField(max_length=100, null=True, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='profession_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='pretestimonialmodel',
            name='sub_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='sub_title'),
        ),
        migrations.AddField(
            model_name='pretestimonialmodel',
            name='sub_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='sub_title'),
        ),
        migrations.AddField(
            model_name='pretestimonialmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='pretestimonialmodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='testimonialimagemodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='testimonialimagemodel',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
