# Generated by Django 4.2.3 on 2023-07-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_pretestimonialmodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreTestimonialModel',
        ),
    ]
