# Generated by Django 4.2.3 on 2023-07-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_delete_pretestimonialmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutImageModel',
        ),
        migrations.AlterModelOptions(
            name='testimonialimagemodel',
            options={'verbose_name': 'testimonial image', 'verbose_name_plural': 'testimonial images'},
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
