# Generated by Django 4.2.3 on 2023-07-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_premenumodel_options_imagemodel_title_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreMenuModel',
        ),
    ]
