# Generated by Django 4.2.3 on 2023-07-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategorymodel', verbose_name='type'),
        ),
    ]
