# Generated by Django 4.2.3 on 2023-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
