# Generated by Django 4.2.3 on 2023-07-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productcategorymodel_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='type',
            new_name='category',
        ),
    ]
