# Generated by Django 4.2.3 on 2023-07-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productmodel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
